name = "EFTfitter"
uuid = "2a2a6a96-a4ec-477f-941b-476720990667"
authors = ["Cornelius Grunwald"]
version = "0.1.0"

[deps]
BAT = "c0cd4b16-88b7-57fa-983b-ab80aecada7e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"

[compat]
BAT = "2"
Distributions = "0.22, 0.23, 0.24"
NamedTupleTools = "0.13"
Parameters = "0.12"
RecipesBase = "0.7, 0.8, 1.0"
Requires = "0.5, 1"
Setfield = "0.7"
StatsBase = "0.32, 0.33"
ValueShapes = "0.7"
julia = "1.3"

[extras]
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["IntervalSets", "Test"]
